version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    volumes:
      - ./data:/app/data  # To persist database file
    depends_on:
      - db

  db:
    image: nouchka/sqlite3  # Use an appropriate image for SQLite
    volumes:
      - ./data:/data  # Persist database
